### ISSUE TITLE
enhancement: Integration Tests

### ISSUE THREAD

**Issue by arein** [WalletConnect/push-server#13]
can be in the sample apps or better a small integration test suite here in the repository.

Personally I like the mocha for integ tests e.g. https://github.com/WalletConnect/registry-api-cf-workers/tree/master/integration

**Comment by thaodt** [comment]
> can be in the sample apps or better a small integration test suite here in the repository.
> 
> Personally I like the mocha for integ tests e.g. https://github.com/WalletConnect/registry-api-cf-workers/tree/master/integration

@arein the ref link seems not found now. Could you please update? how about using [bats](https://github.com/bats-core/bats-core) for integration tests?

**Comment by arein** [comment]
@HarryET any ideas how to actually test this? I think it needs to be e2e with the SDKs

**Comment by HarryET** [comment]
Yeah E2E, or we can have a local suite which calls all the endpoints but maybe that can be part of unit tests
