### ISSUE TITLE
bug: issue with analytics new fields

### ISSUE THREAD

**Issue by dnul** [WalletConnect/push-server#163]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Analytics output is  is not working properly:

data for 19/7

* received_at looks bad for lot's of records: 
* push_provider looks empty for most entries
* topic look null for most entries

### Expected Behavior

* received_at has valid dates
* topic should not be null
* push_provider should not be unknown 

### Steps To Reproduce

run query:

```select * from prod_data_lake.push_messages where dt=date('2023-07-19')```

### Environment

```markdown
- OS:
- rustc:
- cargo:
```

### Anything else?

<img width="683" alt="Screenshot 2023-07-19 at 11 15 06" src="https://github.com/WalletConnect/echo-server/assets/1649066/b0281bdf-cdc6-47e4-aa7c-4ca777c68154">

**Comment by HarryET** [comment]
Investigating now!
