### ISSUE TITLE
fix: alarm notifications disabled

### ISSUE THREAD

**Issue by chris13524** [WalletConnect/push-server#210]
https://github.com/WalletConnect/echo-server/pull/114/files#diff-301fdb9b35fae4b2dd8554c65981149e450f8ebfe68e76dfbf48e2b89f901486R7

**Comment by geekbrother** [comment]
Seems it's related to the #134 as well.

**Comment by chris13524** [comment]
@geekbrother yeah feel free to close that one too once this all works

**Comment by geekbrother** [comment]
I'm re-opening this issue as we have 5xx errors in Graphana dashboard and don't receive opsgenie alerts. Should be investigated further as it seems it's not enough changes we have made.

**Comment by geekbrother** [comment]
Re-opening this issue until 5xx alerts will work as expected
