### ISSUE TITLE
fix: Handling expired APNS certificates properly

### ISSUE THREAD

**Issue by geekbrother** [WalletConnect/push-server#308]
At the moment `Apns(ConnectionError(hyper::Error(Io, Custom { kind: InvalidData, error: "received fatal alert: CertificateExpired" })))` causing a 500 HTTP error.
We should handle properly expired certificates instead of throwing 500 errors.

**Comment by chris13524** [comment]
When this error happens suspend the tenant: https://walletconnect.slack.com/archives/C058RS0MH38/p1710782583542969?thread_ts=1710726001.743679&cid=C058RS0MH38

This will result in a 202 response code not a 5xx.
