### ISSUE TITLE
enhancement: Improve logging of SQL statements

### ISSUE THREAD

**Issue by arein** [WalletConnect/push-server#34]
These shouldn't be multiline logs

<img width="1324" alt="Screen Shot 2022-10-20 at 5 52 49 PM" src="https://user-images.githubusercontent.com/966091/197066083-3fc72020-8126-4462-bdcb-fd537e64ad86.png">

**Comment by HarryET** [comment]
This should have been fixed recently, will validate and then close this with a link to the commit.

**Comment by HarryET** [comment]
This was added in this PR #76
