### ISSUE TITLE
feat: APNS encrypted payload

### ISSUE THREAD

**Issue by llbartekll** [WalletConnect/push-server#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Currently encrypted PNs for APNS are not supported.

### Requested Behavior

Encrypted Push Notifications could have following payload:
```
{"aps":{
     "mutable-content" : 1
},
  "topic": string,
  "ciphertext": string
}
```
payload can be decorated with more properties but those above are required.

**Comment by HarryET** [comment]
Encrypted Push is supported both in the spec and the implementation, see the apns provider. I can provide an example payload later in the issue

**Comment by llbartekll** [comment]
> I can provide an example payload later in the issue

please do it, I need to know what to expect to receive. Is blocking me.

**Comment by HarryET** [comment]
Here is the APNS request that Echo Server now sends for encrypted push
```json
{
  "aps":{
    "content-available":1,
    "mutable-content":1
  },
  "encrypted_payload":{
    "blob":"encrypted-payload",
    "flags":1,
    "topic":"my_topic"
  }
}
```

**Comment by llbartekll** [comment]
ok, so could we change it a little?
1) do we need flag? Could we remove the property for now?
2) can we flatten the `encrypted_payload` for convenience?
 
```
{
  "aps":{
    "content-available":1,
    "mutable-content":1
  },
    "ciphertext":"encrypted-payload",
    "topic":"my_topic"
}
```

**Comment by HarryET** [comment]
> do we need flag? Could we remove the property for now?

I know wallets have asked for the ability to filter the notifications based on their origin e.g. sign (us) or push (others) so I would argue that this should be kept to allow for that

> can we flatten the encrypted_payload for convenience?

Sure

**Comment by llbartekll** [comment]
> I know wallets have asked for the ability to filter the notifications based on their origin e.g. sign (us) or push (others) so I would argue that this should be kept to allow for that

Ok, that makes a lot of sense but could you maybe translate the flag into the `api` param? other ideas? handling flag on mobile side is not convenient and it contains information(is payload encrypted) that is useless.

**Comment by llbartekll** [comment]
flag makes more sense on echo server side

**Comment by HarryET** [comment]
So you would prefer Echo Server filters out the allowed apis and only sends the allowed ones as APNS?

**Comment by HarryET** [comment]
e.g. tenants can configure their allowed APIs

**Comment by llbartekll** [comment]
not really, what I mean is that flag is:

>    - `flags`: an integer value that uses bitmasks to encode information about the payload for the SDKs, the flags are below
    Encrypted  = 1 << 0
    Sign       = 1 << 1
    Auth       = 1 << 2
    Chat       = 1 << 3
    Push       = 1 << 4

and for wallet to have a property like `api` would be more accurate.
e.g.
```
{
  "aps":{
    "content-available":1,
    "mutable-content":1
  },
    "ciphertext":"encrypted-payload",
    "topic":"my_topic",
    "api": "chat"
}
```

**Comment by HarryET** [comment]
> not really, what I mean is that flag is:
> 
> > * `flags`: an integer value that uses bitmasks to encode information about the payload for the SDKs, the flags are below
> >   Encrypted  = 1 << 0
> >   Sign       = 1 << 1
> >   Auth       = 1 << 2
> >   Chat       = 1 << 3
> >   Push       = 1 << 4
> 
> and for wallet to have a property like `api` would be more accurate. e.g.
> 
> ```
> {
>   "aps":{
>     "content-available":1,
>     "mutable-content":1
>   },
>     "ciphertext":"encrypted-payload",
>     "topic":"my_topic",
>     "api": "chat"
> }
> ```

Ah okay we can do that too but tbh I think the filtering could be good too

**Comment by llbartekll** [comment]
or maybe even not `api` but `"origin": "wc_chat"` what do you think? it's more generic.
