### ISSUE TITLE
enhancement: Clippy Config

### ISSUE THREAD

**Issue by HarryET** [WalletConnect/push-server#9]
Create a clippy config and stop using `clippy::all` in CI

**Comment by HarryET** [comment]
This issue is to create a customised Clippy config (to be discussed internally) and use that instead of `clippy::all`

**Comment by thaodt** [comment]
> This issue is to create a customised Clippy config (to be discussed internally) and use that instead of `clippy::all`

@HarryET did you mean using clippy lints for each func/files? Where can I read these discussion if possible? Already joined discord server but it seems quiet there and I didnt see any discussions relating to rust projects.
